### ISSUE TITLE
project.plot_bayes_stats()

### ISSUE THREAD

**Issue by mohamedsobh53** [paudetseis/PlateFlex#5]
Hi Dr. Audet,

I am using PlatFlex to estimate the effective elastic thickness over southern Africa and I have this error during the Plot stats for estimate

TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/pflex/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4410             try:
-> 4411                 return libindex.get_value_at(s, key)
   4412             except IndexError:

pandas/_libs/index.pyx in pandas._libs.index.get_value_at()

pandas/_libs/index.pyx in pandas._libs.index.get_value_at()

pandas/_libs/util.pxd in pandas._libs.util.get_value_at()

pandas/_libs/util.pxd in pandas._libs.util.validate_indexer()

TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/pflex/lib/python3.7/site-packages/plateflex/classes.py in plot_bayes_stats(self, title, save)
   1350                 self.map_estimate, title=title,
-> 1351                 save=save)
   1352         except:

~/anaconda3/envs/pflex/lib/python3.7/site-packages/plateflex/plotting.py in plot_bayes_stats(trace, summary, map_estimate, title, save)
    128     # Extract results from summary and map_estimate
--> 129     results = estimate.get_bayes_estimates(summary, map_estimate)
    130 

~/anaconda3/envs/pflex/lib/python3.7/site-packages/plateflex/estimate.py in get_bayes_estimates(summary, map_estimate)
    201             std_te = row['sd']
--> 202             C2_5_te = row['hpd_2.5']
    203             C97_5_te = row['hpd_97.5']

~/anaconda3/envs/pflex/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
    870         try:
--> 871             result = self.index.get_value(self, key)
    872 

~/anaconda3/envs/pflex/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4418                 else:
-> 4419                     raise e1
   4420             except Exception:

~/anaconda3/envs/pflex/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4404         try:
-> 4405             return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
   4406         except KeyError as e1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'hpd_2.5'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-7-51b1006f137e> in <module>
     12 
     13 # Plot stats for estimate
---> 14 project.plot_bayes_stats()

~/anaconda3/envs/pflex/lib/python3.7/site-packages/plateflex/classes.py in plot_bayes_stats(self, title, save)
   1351                 save=save)
   1352         except:
-> 1353             raise(Exception("No 'cell' estimate available"))
   1354 
   1355     def plot_functions(self, est='mean', title=None, save=None):

Exception: No 'cell' estimate available

**Comment by paudetseis** [comment]
Hi @mohamedsobh53 

Thank you for posting this. The issue is related to an update of PyMC3 that had not been implemented in PlateFlex yet. I just fixed the code and it should work now. You will have to pull the changes, and re-install PlateFlex using `pip install .`. Unless you installed initially with `pip install -e .`, in which case the code will update automatically without the need to re-install.

**Comment by mohamedsobh53** [comment]
Thank you so much for your reply. I re-install it again, but another error appears:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-51b1006f137e> in <module>
      3 
      4 # Perform estimation
----> 5 project.estimate_cell(cell)
      6 
      7 # Print summary

~/anaconda3/envs/pflex/lib/python3.8/site-packages/plateflex/classes.py in estimate_cell(self, cell, alph, atype, returned)
   1107 
   1108         elif self.inverse == 'bayes':
-> 1109             trace, summary, map_estimate = estimate.bayes_estimate_cell(
   1110                 self.k, adm, eadm, coh, ecoh, alph, atype)
   1111 

~/anaconda3/envs/pflex/lib/python3.8/site-packages/plateflex/estimate.py in bayes_estimate_cell(k, adm, eadm, coh, ecoh, alph, atype)
    159 
    160         # Get Summary
--> 161         summary = pm.summary(trace)
    162 
    163     return trace, summary, map_estimate

AttributeError: module 'pymc3' has no attribute 'summary'

**Comment by paudetseis** [comment]
I am not sure what is going on here, since the method `summary` does exist with pymc3: https://docs.pymc.io/api/stats.html 

I can see that your python versions have changed between your first and second post (~/anaconda3/envs/pflex/lib/python3.7 vs ~/anaconda3/envs/pflex/lib/python3.8 in your TraceBack messages). It's possible the versions got mixed up with pymc3. I would recommend doing a clean install of PlateFlex with all dependencies, which involves deleting the conda `pflex` environment and re-creating it.

**Comment by mohamedsobh53** [comment]
Dear Dr. Audet,

I followed what you recommend and the same error paper. Kindly find an attached a screenshot from my machine. 

![Screenshot from 2021-02-17 14-48-51](https://user-images.githubusercontent.com/66426862/108213522-69f50900-712f-11eb-9899-68c979dc7233.png)

**Comment by paudetseis** [comment]
Ok, I figured out what the problem was. It's again related to PyMC3. The new version of PyMC3 is 3.11, which has gotten rid of all the stats methods (see here: https://github.com/pymc-devs/pymc3/blob/master/RELEASE-NOTES.md) including the `summary` method. To fix PlateFlex, please do the following steps:

- remove your pflex environment (`conda env remove --name pflex`)
- re-create the pflex environment by specifying pymc3=3.10 (`conda create -n pflex python=3.8 fortran-compiler numpy pymc3=3.10 matplotlib seaborn scikit-image -c conda-forge`)
- activate pflex and re-install jypyter (`conda activate pflex`; `conda install jupyter`)
- re-install PlateFlex (`pip install .`)

It should work now. I added a note in the documentation to use pymc3=3.10 until I can figure out how to update PlateFlex to use pymc3=3.11.

**Comment by mohamedsobh53** [comment]
Dear Dr. Audet,

Thank you so much!. It works fine now. I appreciate your help

Best,
Mohamed Sobh
